[package]
name = "tiny_renderer"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.9.0"
winit = "0.26"
winit_input_helper = "0.11"
obj-rs = "0.7.0"